/** Stable schedule / time error codes. */
export const TimeErrors = Object.freeze({
  INVALID_TIME_ZONE: "INVALID_TIME_ZONE",
  INVALID_TIMESTAMP: "INVALID_TIMESTAMP",
  TIMESTAMP_OFFSET_REQUIRED: "TIMESTAMP_OFFSET_REQUIRED",
  INVALID_RECURRENCE: "INVALID_RECURRENCE",
  SCHEDULE_END_BEFORE_START: "SCHEDULE_END_BEFORE_START",
  SCHEDULE_CONFLICT: "SCHEDULE_CONFLICT",
  SCHEDULE_NOT_ACTIVE: "SCHEDULE_NOT_ACTIVE",
  SCHEDULE_OCCURRENCE_ALREADY_PROCESSED: "SCHEDULE_OCCURRENCE_ALREADY_PROCESSED",
  SCHEDULE_OCCURRENCE_IN_PROGRESS: "SCHEDULE_OCCURRENCE_IN_PROGRESS",
  SCHEDULE_OCCURRENCE_MISSED: "SCHEDULE_OCCURRENCE_MISSED",
  SCHEDULE_OCCURRENCE_EXPIRED: "SCHEDULE_OCCURRENCE_EXPIRED",
  NONEXISTENT_LOCAL_TIME: "NONEXISTENT_LOCAL_TIME",
  AMBIGUOUS_LOCAL_TIME: "AMBIGUOUS_LOCAL_TIME",
  RESET_PERIOD_NOT_FOUND: "RESET_PERIOD_NOT_FOUND",
  CLAIM_WINDOW_CLOSED: "CLAIM_WINDOW_CLOSED",
  EVENT_NOT_STARTED: "EVENT_NOT_STARTED",
  EVENT_ENDED: "EVENT_ENDED",
  TRADE_EXPIRED: "TRADE_EXPIRED",
  MAIL_EXPIRED: "MAIL_EXPIRED",
  COOLDOWN_ACTIVE: "COOLDOWN_ACTIVE",
});

export class TimeError extends Error {
  constructor(code, message, details = null) {
    super(message || code);
    this.name = "TimeError";
    this.code = code;
    this.details = details;
  }
}
