/** Stable reward error codes. */
export const RewardErrors = Object.freeze({
  REWARD_NOT_FOUND: "REWARD_NOT_FOUND",
  REWARD_NOT_ELIGIBLE: "REWARD_NOT_ELIGIBLE",
  REWARD_ALREADY_CLAIMED: "REWARD_ALREADY_CLAIMED",
  REWARD_EXPIRED: "REWARD_EXPIRED",
  REWARD_DEFINITION_INVALID: "REWARD_DEFINITION_INVALID",
  REWARD_GENERATION_FAILED: "REWARD_GENERATION_FAILED",
  REWARD_DELIVERY_FAILED: "REWARD_DELIVERY_FAILED",
  INVENTORY_FULL: "INVENTORY_FULL",
  REWARD_SENT_TO_OVERFLOW: "REWARD_SENT_TO_OVERFLOW",
  FEATURE_DISABLED: "FEATURE_DISABLED",
  INVALID_REWARD_SOURCE: "INVALID_REWARD_SOURCE",
  REWARD_LIMIT_EXCEEDED: "REWARD_LIMIT_EXCEEDED",
  REWARD_CONFIGURATION_UNAVAILABLE: "REWARD_CONFIGURATION_UNAVAILABLE",
  CLAIM_IN_PROGRESS: "CLAIM_IN_PROGRESS",
  IDEMPOTENCY_PAYLOAD_MISMATCH: "IDEMPOTENCY_PAYLOAD_MISMATCH",
  IDEMPOTENCY_KEY_REQUIRED: "IDEMPOTENCY_KEY_REQUIRED",
  CHARACTER_NOT_OWNED: "CHARACTER_NOT_OWNED",
  MISSION_NOT_COMPLETE: "MISSION_NOT_COMPLETE",
  SUSPICIOUS_CLIENT_PAYLOAD: "SUSPICIOUS_CLIENT_PAYLOAD",
  FORBIDDEN: "FORBIDDEN",
  REASON_REQUIRED: "REASON_REQUIRED",
});

export class RewardError extends Error {
  constructor(code, message, details = null) {
    super(message || code);
    this.name = "RewardError";
    this.code = code;
    this.details = details;
  }
}
