export class ArenaError extends Error {
  constructor(code, message, status = 400, details = null) {
    super(message);
    this.code = code;
    this.status = status;
    this.details = details;
  }
}

export const ArenaErrors = {
  ARENA_CHALLENGE_NOT_ALLOWED: "ARENA_CHALLENGE_NOT_ALLOWED",
  ARENA_OPPONENT_NOT_ELIGIBLE: "ARENA_OPPONENT_NOT_ELIGIBLE",
  ARENA_CANNOT_CHALLENGE_SELF: "ARENA_CANNOT_CHALLENGE_SELF",
  ARENA_SAME_ACCOUNT_CHALLENGE: "ARENA_SAME_ACCOUNT_CHALLENGE",
  ARENA_CHALLENGE_COOLDOWN: "ARENA_CHALLENGE_COOLDOWN",
  ARENA_ACTIVE_CHALLENGE_EXISTS: "ARENA_ACTIVE_CHALLENGE_EXISTS",
  ARENA_OPPONENT_TOO_LOW_FOR_RATING_GAIN: "ARENA_OPPONENT_TOO_LOW_FOR_RATING_GAIN",
  ARENA_REPEAT_OPPONENT_REDUCED_REWARD: "ARENA_REPEAT_OPPONENT_REDUCED_REWARD",
  ARENA_REPEAT_OPPONENT_NO_RATING: "ARENA_REPEAT_OPPONENT_NO_RATING",
  ARENA_CHALLENGE_EXPIRED: "ARENA_CHALLENGE_EXPIRED",
  ARENA_SEASON_INACTIVE: "ARENA_SEASON_INACTIVE",
  ARENA_DEFENSE_SNAPSHOT_UNAVAILABLE: "ARENA_DEFENSE_SNAPSHOT_UNAVAILABLE",
  ARENA_RATING_POLICY_CHANGED: "ARENA_RATING_POLICY_CHANGED",
  ARENA_CHALLENGE_NOT_FOUND: "ARENA_CHALLENGE_NOT_FOUND",
  ARENA_CHALLENGE_NOT_OWNED: "ARENA_CHALLENGE_NOT_OWNED",
  ARENA_CHALLENGE_ALREADY_COMPLETED: "ARENA_CHALLENGE_ALREADY_COMPLETED",
  ARENA_IDEMPOTENCY_CONFLICT: "ARENA_IDEMPOTENCY_CONFLICT",
  ARENA_CHARACTER_NOT_OWNED: "ARENA_CHARACTER_NOT_OWNED",
  ARENA_INVALID_REQUEST: "ARENA_INVALID_REQUEST",
  ARENA_NO_PENDING_COMBAT: "ARENA_NO_PENDING_COMBAT",
  ARENA_PENDING_COMBAT: "ARENA_PENDING_COMBAT",
};
