param(
    [string]$Version = "0.1.0",
    [string]$GodotPath = "",
    [string]$InnoCompilerPath = ""
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$ProjectDir = Join-Path $Root "loot&lasers"
$ReleaseConfig = Join-Path $ProjectDir "Config\release_client.cfg"
$ExportDir = Join-Path $Root "dist\windows"
$ExportExe = Join-Path $ExportDir "LootAndLasers.exe"
$InstallerScript = Join-Path $Root "installer\LootAndLasers.iss"

function Resolve-Executable {
    param(
        [string]$ExplicitPath,
        [string[]]$Candidates,
        [string]$Label
    )

    if ($ExplicitPath -and (Test-Path $ExplicitPath)) {
        return (Resolve-Path $ExplicitPath).Path
    }
    foreach ($candidate in $Candidates) {
        if (-not $candidate) { continue }
        $command = Get-Command $candidate -ErrorAction SilentlyContinue
        if ($command) { return $command.Source }
        if (Test-Path $candidate) { return (Resolve-Path $candidate).Path }
    }
    throw "$Label was not found. Install it or pass its path explicitly."
}

$Godot = Resolve-Executable -ExplicitPath $GodotPath -Label "Godot 4.7.1" -Candidates @(
    "godot",
    "godot4",
    (Join-Path $env:USERPROFILE "Downloads\Godot_v4.7.1-stable_win64.exe\Godot_v4.7.1-stable_win64_console.exe"),
    (Join-Path $env:USERPROFILE "Downloads\Godot_v4.7.1-stable_win64.exe\Godot_v4.7.1-stable_win64.exe")
)

$Inno = Resolve-Executable -ExplicitPath $InnoCompilerPath -Label "Inno Setup Compiler" -Candidates @(
    "ISCC.exe",
    (Join-Path ${env:ProgramFiles(x86)} "Inno Setup 6\ISCC.exe"),
    (Join-Path $env:LOCALAPPDATA "Programs\Inno Setup 6\ISCC.exe")
)

$Key = $env:NAKAMA_SOCKET_SERVER_KEY
if ([string]::IsNullOrWhiteSpace($Key)) {
    $Key = [Environment]::GetEnvironmentVariable("NAKAMA_SOCKET_SERVER_KEY", "User")
}
if ($Key -notmatch "^[0-9a-fA-F]{64}$") {
    throw "NAKAMA_SOCKET_SERVER_KEY must be the 64-character hexadecimal staging client key."
}

New-Item -ItemType Directory -Force -Path $ExportDir | Out-Null
$releaseConfigContents = @"
; Generated by scripts/build-windows-installer.ps1. Never commit this file.
[staging]
server_key="$Key"
"@

try {
    Set-Content -Path $ReleaseConfig -Value $releaseConfigContents -Encoding UTF8

    & $Godot --headless --path $ProjectDir --export-release "Windows Staging" $ExportExe
    if ($LASTEXITCODE -ne 0 -or -not (Test-Path $ExportExe)) {
        throw "Godot Windows export failed."
    }

    & $Inno "/DMyAppVersion=$Version" $InstallerScript
    if ($LASTEXITCODE -ne 0) {
        throw "Inno Setup compilation failed."
    }
}
finally {
    Remove-Item -Path $ReleaseConfig -Force -ErrorAction SilentlyContinue
}

$Installer = Join-Path $Root "dist\LootAndLasers-Setup-$Version.exe"
if (-not (Test-Path $Installer)) {
    throw "Installer output was not created at $Installer"
}

Write-Host "Installer ready:"
Write-Host $Installer
