/** Entity types and import order (parents before children). */
export const ENTITY_TYPES = [
  "AppNotification", "Block", "Character", "ChatMessage", "DailyLogin",
  "FriendRequest", "Friendship", "GalaxyNews", "Guild", "GuildBattle",
  "GuildChallenge", "GuildLog", "GuildMember", "GuildWar", "GuildWarReady",
  "HubLayout", "Item", "Mail", "Mission", "ModerationConfig", "Nexus",
  "NexusAssault", "NexusHallOfFame", "NovaSpendEvent", "StardustSpendEvent", "PlayerModeration",
  "PlayerPresence", "PrivateConversation", "PrivateMessage", "PromoCode",
  "Report", "SiteConfig", "User",
];

/** Recommended import order — FK-safe for typical game data. */
export const IMPORT_ORDER = [
  "User",
  "Character",
  "Item",
  "Mission",
  "DailyLogin",
  "PlayerPresence",
  "PlayerModeration",
  "Mail",
  "AppNotification",
  "Guild",
  "GuildMember",
  "GuildLog",
  "GuildChallenge",
  "GuildBattle",
  "GuildWar",
  "GuildWarReady",
  "Friendship",
  "FriendRequest",
  "Block",
  "Report",
  "ChatMessage",
  "PrivateConversation",
  "PrivateMessage",
  "GalaxyNews",
  "NexusAssault",
  "NexusHallOfFame",
  "NovaSpendEvent",
  "PromoCode",
  "HubLayout",
  "ModerationConfig",
  "Nexus",
  "SiteConfig",
];
