/**
 * Stable entitlement error codes.
 */
export const EntitlementErrors = Object.freeze({
  ENTITLEMENT_NOT_FOUND: "ENTITLEMENT_NOT_FOUND",
  ENTITLEMENT_NOT_OWNED: "ENTITLEMENT_NOT_OWNED",
  ENTITLEMENT_INACTIVE: "ENTITLEMENT_INACTIVE",
  ENTITLEMENT_EXPIRED: "ENTITLEMENT_EXPIRED",
  ENTITLEMENT_SUSPENDED: "ENTITLEMENT_SUSPENDED",
  ENTITLEMENT_REVOKED: "ENTITLEMENT_REVOKED",
  ENTITLEMENT_REFUNDED: "ENTITLEMENT_REFUNDED",
  ENTITLEMENT_CHARGEBACK: "ENTITLEMENT_CHARGEBACK",
  ENTITLEMENT_NOT_STARTED: "ENTITLEMENT_NOT_STARTED",
  ENTITLEMENT_CONSUMED: "ENTITLEMENT_CONSUMED",
  ENTITLEMENT_QUANTITY_INSUFFICIENT: "ENTITLEMENT_QUANTITY_INSUFFICIENT",
  ENTITLEMENT_SCOPE_MISMATCH: "ENTITLEMENT_SCOPE_MISMATCH",
  ENTITLEMENT_FEATURE_DISABLED: "ENTITLEMENT_FEATURE_DISABLED",
  ENTITLEMENT_UNKNOWN_KEY: "ENTITLEMENT_UNKNOWN_KEY",
  PURCHASE_VERIFICATION_REQUIRED: "PURCHASE_VERIFICATION_REQUIRED",
  PURCHASE_VERIFICATION_FAILED: "PURCHASE_VERIFICATION_FAILED",
  PURCHASE_ALREADY_CLAIMED: "PURCHASE_ALREADY_CLAIMED",
  EXTERNAL_TRANSACTION_REUSED: "EXTERNAL_TRANSACTION_REUSED",
  PRODUCT_NOT_REGISTERED: "PRODUCT_NOT_REGISTERED",
  SUBSCRIPTION_INACTIVE: "SUBSCRIPTION_INACTIVE",
  SUBSCRIPTION_VERIFICATION_PENDING: "SUBSCRIPTION_VERIFICATION_PENDING",
  CHARACTER_SLOT_LIMIT_REACHED: "CHARACTER_SLOT_LIMIT_REACHED",
  IDEMPOTENCY_PAYLOAD_MISMATCH: "IDEMPOTENCY_PAYLOAD_MISMATCH",
  IDEMPOTENCY_KEY_REQUIRED: "IDEMPOTENCY_KEY_REQUIRED",
  REASON_REQUIRED: "REASON_REQUIRED",
  FORBIDDEN: "FORBIDDEN",
});

export class EntitlementError extends Error {
  constructor(code, message, details = null) {
    super(message || code);
    this.name = "EntitlementError";
    this.code = code;
    this.details = details;
  }
}
